# Generated by Django 3.1.3 on 2021-05-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_donationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationhistory',
            name='order_total',
        ),
        migrations.RemoveField(
            model_name='donationhistory',
            name='stripe_pid',
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='package',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
