# Generated by Django 3.1.3 on 2021-04-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210412_1918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
